import express from 'express';
import cors from 'cors';
import { initDb } from './models/db';
import authRoutes from './routes/auth';
import ledgerRoutes from './routes/ledger';
import performanceRoutes from './routes/performance';
const app = express();
initDb();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/ledger', ledgerRoutes);
app.use('/api/performance', performanceRoutes);
app.get('/health', (req, res) => res.json({ status: 'UP' }));
app.listen(3001, () => console.log('Backend on 3001'));
